### ISSUE TITLE
Question what is the text command

### ISSUE THREAD

**Issue by millerthegorilla** [jimholgate/readtextextension#10]
Hi, I have installed google_speech on linux and want to use it to read some text that I've highlighted in libreoffice writer.

What is the variable that refers to the text pls?  I have seen that:
    
    (OOO_WEBTEXT)

works with google_speech, only it escapes the text with html encoded spaces etc.  Is there a variable name such as (TEXT) that I can use?
If I use (TMP) the path to the textfile is read out, but not the contained text.
Many thanks

**Comment by millerthegorilla** [comment]
I found this, but it doesn't have a code for the unencoded text.
https://github.com/jimholgate/readtextextension/blob/master/wiki/CommandAndScriptTokens.wiki

**Comment by millerthegorilla** [comment]
I have edited the script from google_speech to include urllib.parse.unquote
as follows:

    #!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys
import urllib.parse

from google_speech import cl_main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.argv[1] = urllib.parse.unquote(sys.argv[1])
    sys.exit(cl_main())

This allows me to use (OOO_WEBTEXT)
google_speech script is available at https://github.com/desbma/GoogleSpeech

**Comment by jimholgate** [comment]
There are no plans to implement an unescaped selected text token to the extension's command line options because providing unfiltered text to a command line is a security risk. Your script or program should be able to read a plain text file using the `(TMP)` token.
