### ISSUE TITLE
Not really an issue ...

### ISSUE THREAD

**Issue by dgcasey0325** [jimholgate/readtextextension#11]
This is more of a feature request.

I like the way Read Text integrates with LibreOffice and have been using it for a couple of weeks now. What I'd like to see built into the program is a set of Pause, Play, Stop buttons on the toolbar. And then have the ability to have the extension start reading from the cursor, rather than having to highlight text or copy to the clipboard.

Other than that, bangin' job, guys. I like it.

**Comment by DoctorSubtilis** [comment]
+1

**Comment by jimholgate** [comment]
> Not really an issue

Thanks for your feedback. There are no plans to add this functionality to this extension.

You might care to investigate [PicoVoxOoo](http://lirecouleur.arkaline.fr/2013/11/11/picosvoxooo/).

![It includes seven playback controls](http://lirecouleur.arkaline.fr/wp-content/uploads/2013/11/barre_picosvoxooo.png)

It includes some playback buttons, but I am not sure if it will work with current versions of LibreOffice or Apache OpenOffice on all platforms. The message on the website indicates that the extension is not under active maintenance by the original author.
