### ISSUE TITLE
How get the box of choice again

### ISSUE THREAD

**Issue by DoctorSubtilis** [jimholgate/readtextextension#14]
How get the box of choice again (once unchecked open this dialog again)?
In tools - add-ons I cannot edit "options";
![bug estensioni LibreOffice (opzioni non settabili)](https://user-images.githubusercontent.com/20089138/55334939-81bf3780-549a-11e9-9675-5ea4adb28025.png)

Thank you very much!

**Comment by AngrySockPuppet** [comment]
Do you mean which TTS option is set as the default?
![image](https://user-images.githubusercontent.com/26633265/55335487-0042b780-5450-11e9-8b46-7108cc431bf9.png)
If your selection is not retained and you're using Windows, clearing out the LibreOffice settings can help.
I experienced this issue and resolved it by following Jim's instructions here...
[Windows 7 - corrupt LibreOffice local settings](https://sites.google.com/site/readtextextension/home/announcements/windows7-corruptlibreofficelocalsettings) 
    Quit LibreOffice.
    Open the Command Prompt (terminal) application.
    It will open in your home directory.
    Type cd AppData.
    Type cd Roaming.
    Type rmdir /s LibreOffice or move LibreOffice LibreOffice.old.
    If prompted to confirm, then type y, then return.
    Restart LibreOffice.
    Wait a few seconds for the application to rebuild the settings directory and set the default settings.
    Quit LibreOffice.
    Restart LibreOffice.
    Reinstall your extensions.
    Restart LibreOffice.

**Comment by DoctorSubtilis** [comment]
Thank you. I mean that dialog, yes. But I use Linux, sorry.

**Comment by jimholgate** [comment]
If I understand your question correctly, you are asking how to view the setup window once you have deselected the _Always show this dialog_ checkbox. 

+ *Tools - Add-Ons - Read Selection...*
+ Click the _Always show this dialog_ checkbox.
+ Experiment with the settings.
+ When you are finished, deselect the _Always show this dialog_ checkbox.

In most modern Linux desktops, the local settings are in the `$HOME/.config/libreoffice` directory. You can reset all LibreOffice settings by quitting the application, then entering the following in a linux terminal: 

```
mv  $HOME/.config/libreoffice  $HOME/.config/libreoffice.old
