### ISSUE TITLE
problem with pico

### ISSUE THREAD

**Issue by DoctorSubtilis** [jimholgate/readtextextension#15]
I found that read-text extension is better with python+pico than with espeak.  
But I cannot set properly pico:

### 1 bug: "--visible=false"

But with python+pico I cannot set, for example

    "(PICO_READ_TEXT_PY)" --language=(SELECTION_LANGUAGE_COUNTRY_CODE) --visible=false "(TMP)"

lest I get a window of VLC freezing (infinite loop without sound, and so I have to kill that task);  in other words the code 

    --visible=false  

is not working: I see a window, but a *crazy* window.

### 2 bug  

When I set pico as following:  

    "(PICO_READ_TEXT_PY)" --language=(SELECTION_LANGUAGE_COUNTRY_CODE) "(TMP)"  

I get a window of mplayer, which correctly play the word selected, but  

 * I cannot set the **volume** at all
 * I see that window: how can avoid a visible window (as in read-text -> espeak)?

Thanks

My OS: Kubuntu 18.04
LO: 6.0.7.3

**Comment by jimholgate** [comment]
I tested VLC on Ubuntu 18.04 LTS and it seems that currently it does not work for this particular application. I [removed](https://github.com/jimholgate/readtextextension/commit/801082d8525016d169a1328845a90477677a6dd1#diff-8e3f2ed827b3ce6749eb77c6392720c3) mentions of the [VLC media player](https://raw.githubusercontent.com/jimholgate/readtextextension/master/Read_Text/python/readtexttools.py) from the python `readtexttools` library for the extension. This fixes the problem. Until the modified version is released, you could make audio work by installing a player with a gstreamer backend like [Rhythm box](https://help.gnome.org/users/rhythmbox/stable/) or [Totem](https://help.gnome.org/users/totem/stable/).

**Comment by jimholgate** [comment]
Fixed in current release.
