### ISSUE TITLE
It's not working on macOS big sur

### ISSUE THREAD

**Issue by artiblaster** [jimholgate/readtextextension#17]
I tried a couple of times. I reinstalled too. It was working on macOS 10, but not on 11. I click the extension in the top left and I see a loading bar on the bottom, but nothing happens.

**Comment by jimholgate** [comment]
For the most recent release of LibreOffice please try [ReadText 0.8.52](https://extensions.openoffice.org/en/projectrelease/read-text-0852) on the OpenOffice.org extensions website. I've lost the ability to update the extension version on the LibreOffice extension website for the moment, but I'm waiting for them to respond to an email.

The version that works with the most recent version of Apache OpenOffice is [Read Text 0.8.53](https://extensions.openoffice.org/en/projectrelease/read-text-0853), also hosted on the Apache OpenOffice website.
