### ISSUE TITLE
LO 7 + BigSur Script crashes

### ISSUE THREAD

**Issue by GuidoBo** [jimholgate/readtextextension#18]
Hi,
Entering the external program **/usr/bin/say** works fine, but when I enter the next field to enter 
` -f "(TMP)"` there the script crashed and I am promoted to **line #1329** in `TTS_Utilities`

`s1 = "-o ""(HOME)(NOW)" & s2(n) & """ -f ""(TMP)"""`

Error reads "`BASIC runtime error: Procedure sub or function not defined`"

We use this extension on Linux and Windows and everything works just fine there. Hope you can fix this soon.

**Comment by jimholgate** [comment]
For the most recent release of LibreOffice please try [ReadText 0.8.52](https://extensions.openoffice.org/en/projectrelease/read-text-0852) on the OpenOffice.org extensions website. I've lost the ability to update the extension version on the LibreOffice extension website for the moment, but I'm waiting for them to respond to an email.

The version that works with the most recent version of Apache OpenOffice is [Read Text 0.8.53](https://extensions.openoffice.org/en/projectrelease/read-text-0853), also hosted on the Apache OpenOffice website.
