### ISSUE TITLE
Could this be used with Coqui TTS or other up to date TTS engine?

### ISSUE THREAD

**Issue by viendocraz** [jimholgate/readtextextension#22]
Just wondering if this extension could be used with an up to date TTS engine like Coqui TTS?  
https://github.com/coqui-ai/TTS  

Or perhaps something like Tortoise TTS?  
https://github.com/neonbjb/tortoise-tts  

If so, if anybody knows how to achieve this, I would be grateful for any help.

**Comment by jimholgate** [comment]
Please see the release notes for version 0.8.66

> Support for developer-oriented speech servers – [Mycroft Mimic3](https://mycroft.ai/mimic-3/) and [CoquiAI TTS](https://coqui.ai/).

-- "[Read Text 0.8.66](https://sites.google.com/site/readtextextension/home/downloads/download-2023-05-28)". *Read Text Extension*. Accessed June 2, 2023.
