### ISSUE TITLE
Impossible to configure path to a personnal script

### ISSUE THREAD

**Issue by rcspam** [jimholgate/readtextextension#24]
Hi,
Impossible to configure a personnal script that use a non standard path to python on linux:

i have create a personal python TTS script that i can't use because this extension reinitiate the python3 path to : /usr/bin/python3.
But i want to set the path to another. ie: miniconda path.

**Comment by jimholgate** [comment]
**Read Text 0.8.74**

Allow or deny access to third party scripts depending on the Office version and whether “Enable experimental features” in the “Options” or “Preferences” menu is enabled. *(Resolves [GitHub Issue 24](https://github.com/jimholgate/readtextextension/issues/24))*.
