### ISSUE TITLE
can't stop speech in LibreOffice

### ISSUE THREAD

**Issue by MarcRochkind** [jimholgate/readtextextension#7]
With the Read Text extension, I see that clicking on the toolbar icon is supposed to stop the speech in progress. However, all it does is start another speech.

LibreOffice Version: 5.0.2.2
Read Text version 0.8.30

**Comment by jimholgate** [comment]
Thank you for reporting the bug. 

Unfortunately without more information about your system, version and settings, it is not possible to track down the origin of the problem. Please provide information on your system and the settings used in the main dialogue so it is possible to try to reproduce the problem. 

To be certain the reported issue is not related to corruption in the user profile, could you rename your [LibreOffice user directory](https://wiki.documentfoundation.org/UserProfile#Default_location) or [profile files](http://ask.libreoffice.org/en/question/903/where-are-the-libreoffice-data-profile-files/ ), reinstall the extension and re-test?

**Comment by jimholgate** [comment]
Did not reproduce error with current version.
