### ISSUE TITLE
Cannot install on Libre Office 4.4

### ISSUE THREAD

**Issue by liladude** [jimholgate/readtextextension#8]
I cannot install the extension on my Libre Office 4.4 installation, even though I was trying to update 0.8.13.
The installation fails because required reference version of OpenOffice 3.5 is not found. Please note that I am using the 0.8.31 file from Open Office repository since I cannot find download link on Libre Office extension repository (link https://extensions.libreoffice.org/extension-center/read-text on main page is broken, suggested link https://extensions.libreoffice.org/extensions/read-text has no download, as far as i can see! I am using Libre Office 4.4 on windows in Italian.

**Comment by kumrzz** [comment]
a bit convoluted but the second link you refer to points at "Homepage of the project" (currently hosted on google.com), which has a "get it" link(currently http://extensions.services.openoffice.org/en/project/read-text): this page in turn, has a clear download link marked "download extension"(points to the sourceforge download currently): this is the badger you're looking for :D

**Comment by jimholgate** [comment]
The current version is available on the [LibreOffice extensions website](https://extensions.libreoffice.org/extensions/read-text/0-8.32) as well as the Apache OpenOffice website.
