### ISSUE TITLE
Incorrect StarBASIC syntax: missing closing parenthesis

### ISSUE THREAD

**Issue by mikekaganski** [jimholgate/readtextextension#9]
With a recent changes in LibreOffice StarBasic parser (https://bugs.documentfoundation.org/show_bug.cgi?id=80731), it now doesn't silently accept a missing closing parenthesis anymore (as it did before). So, this change has revealed a number of extensions that had this flaw unnoticed (https://bugs.documentfoundation.org/show_bug.cgi?id=106529), Read Text being among them (https://ask.libreoffice.org/en/question/90653/after-upgrading-to-5312-previous-working-extensions-results-in-error/).

**Comment by jimholgate** [comment]
Thanks, Mike. Thanks for pointing out the flaw. [This][1] commit adds the closing parenthesis: 

[1]: https://github.com/jimholgate/readtextextension/commit/3ee933396d6571017cc8fd581c9aa051e1ad2726
